config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    resources :comments
  end

  root "posts#index"
  get '/about', to: "page#about"
  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true,length:{minimum: 5}
  validates :content,presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post=Post.find(params[:post_id])
    @comment=@post.comments.create(params[:comment].permit(:name,:body))
    redirect_to post_path(@post)
  end
  def destroy
    @post=Post.find(params[:post_id])
    @comment=@post.comments.find(params[:id])
    @comment.destroy
    redirect_to :back
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!,except: [:index,:show]
	def index
		@posts=Post.all.order('created_at DESC')
	end

	def new
		@post=Post.new
	end

	def create
		@post=Post.new(postparams)

		if @post.save
			redirect_to @post
		else
			render "new"
		end
	end

	def edit
		@post=Post.find(params[:id])
	end

	def update
		@post=Post.find(params[:id])
		if @post.update(params[:post].permit(:title,:content))
			redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		@post=Post.find(params[:id])
		@post.destroy
		redirect_to :root
	end

	def show
		@post=Post.find(params[:id])
	end
	private
	def postparams
		params.require(:post).permit(:title, :content)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
  <div class="comment_content">
    <p class="comment_name"><%=comment.name%></p>
    <p class="comment_body"><%=comment.body%></p>
    <p class="comment_time"><%= time_ago_in_words(comment.created_at)%> Ago</p>
  </div>
  <p>
  <%= link_to "delete",[comment.post,comment],method: :delete,class: "button",data: {confirm: "are you sure?"}%>
  </p>
</div>

app/views/comments/_form.html.erb
<%=form_for([@post,@post.comments.build]) do |f|%>
<p><%= f.label :name%><br>
<%= f.text_field :name%></p>
<p><%= f.label :body%><br>
<%= f.text_area :body%></p>
<p><%= f.submit%></p>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href="https://fonts.googleapis.com/css?family=Raleway:400,700" rel="stylesheet">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="sidebar">
    <div id="logo">
      <%=link_to root_path do%>
      <%=image_tag "Winter_Is_Coming.png"%>
      <% end %>
    </div>
    <ul>
      <li><%=link_to "Blog",root_path %></li>
      <li><%=link_to "About","/about"%></li>
    </ul>
    <ul>
      <li class="category">Social</li>
      <li><a href="https://www.facebook.com/ankush.malik.5680">Facebook</a></li>
      <li><a href="https://twitter.com/iamankushmalik">Twitter</a></li>
      <li><a href="https://www.instagram.com/iam.ankush/">Instagram</a></li>
    </ul>
    <% if !user_signed_in?%>
    <p class="sign_in">
      <%= link_to "Admin_Login",new_user_session_path%>
    </p>
    <%end%>
  </div>

  <div id="main_content">
    <div id="header">
      <%if current_page?(root_path)%>
      <p>All Posts</p>
      <%elsif current_page?(about_path)%>
      <p>About Page</p>
      <%else%>
      <%= link_to"Back",root_path,class:"button"%>
      <%end%>
      <%if user_signed_in? %>
        <div class="buttons">
          <button class="button"><%= link_to "New Post",new_post_path%></button>
          <button class="button"><%= link_to "Log Out",destroy_user_session_path,method: :delete%></button>
        </div>
      <%end%>
    </div>
    <%flash.each do|name,msg|%>
      <%= content_tag(:div,msg,class: "alert")%>
    <% end %>
    <%= yield %>
  </div>

</body>
</html>

app/views/page/about.html.erb
<div id="page_wrapper">
  <div style="display:flex;">
  <%=image_tag "me.jpg",style:"height:250px;width:250px; display inline;"%>
  <div style="padding:25px;">
    <p style="max-width:450px;padding-bottom:4px;">A web developer/designer and core-java enthusiast from New Delhi,India. I enjoy building things from scratch, writing pretty code, black coffee, and the oxford semi colon.</p>
    <p style="max-width:450px;padding-bottom:4px;">Currently pursuing B.tech(CSE) from Maharaja Agrasen Institute of Technology(2015-2019)</p>
    <p style="max-width:450px;padding-bottom:4px;">If you're looking for some of my work, you've come to the right place.</p>
  </div>
  </div>
</div>

app/views/posts/_form.html.erb
<%=form_for @post do |f| %>
 <%if @post.errors.any? %>
    <div id="errors">
      <h3><%=pluralize(@post.errors.count,"errors")%> prevented from saving this post</h3>
        <ul>
          <% @post.errors.full_messages.each do |msg|%>
          <li><%= msg %></li>
          <%end%>
        </ul>
    </div>
 <%end%>
<p><%= f.label :title%><br>
<%= f.text_field :title%></p>
<p><%= f.label :content%><br>
<%= f.text_area :content%></p>
<p><%= f.submit%></p>
<%end%>

app/views/posts/edit.html.erb
<div id="page_wrapper">
  <h1>Edit Post</h1>
  <%= render "form"%>
</div>

app/views/posts/index.html.erb
  <% @posts.each do |post|%>
    <div class="post_wrapper">
      <h2 class="title"><%= link_to post.title,post %></h2>
      <p class="date"><%= post.created_at.strftime("%B,%d,%Y")%></p>
    </div>
  <% end %>

app/views/posts/new.html.erb
<div id="page_wrapper">
  <h1>New Post</h1>
  <%= render "form"%>
</div>

app/views/posts/show.html.erb
<div id="post_content">
  <h1 class="title">
    <%=@post.title%>
  </h1>
  <h6 class="date">
    created <%=time_ago_in_words(@post.created_at)%> ago |
    <%= link_to "Edit",edit_post_path(@post)%> |
    <%=link_to "delete",@post,method: :delete,data: {confirm: "are you sure?"}%>
  </h6><br>
  <p class="body">
    <%=@post.content%>
  </p><br>
  <div id="comments">
    <h2><%=pluralize(@post.comments.count,"Comments")%></h2>
    <%= render @post.comments %>
    <h3>Add a comment:</h3>
    <%= render "comments/form"%>
  </div>
</div>